sudo: required

install: true

services:
  - docker

script:
  - docker build -t tutorabcvfe/chrome-headless:latest ./

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push tutorabcvfe/chrome-headless:latest;
    fi